version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=public.ecr.aws/h2v1o9z6/grpc-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI/server:latest -f ./server/Dockerfile .
      - docker tag $REPOSITORY_URI/server:latest $REPOSITORY_URI/server:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI/client:latest -f ./client/Dockerfile .
      - docker tag $REPOSITORY_URI/client:latest $REPOSITORY_URI/client:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/server:latest
      - docker push $REPOSITORY_URI/server:$IMAGE_TAG
      - docker push $REPOSITORY_URI/client:latest
      - docker push $REPOSITORY_URI/client:$IMAGE_TAG
