apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: client
          image: public.ecr.aws/h2v1o9z6/grpc-app/client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          