apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30727
      protocol: TCP
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
  labels:
    app: grpc-client
spec:
  selector:
    app: grpc-client
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30728
      protocol: TCP
  type: NodePort